version = 0.1
[default.deploy.parameters]
stack_name = "team2-s3-presignedurl-gen-lambdav2"
resolve_s3 = true
s3_prefix = "team2-s3-presignedurl-gen-lambdav2"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
